services:
  db:
    image: mariadb:${MARIADB_TAG}
    container_name: wp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./data/db:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: wp-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis-data:/data

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        WORDPRESS_TAG: ${WORDPRESS_TAG}
        PUID: ${PUID}
        PGID: ${PGID}
    container_name: wp-php
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('FS_METHOD', 'direct');
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_DISABLED', false);
        define('DISABLE_WP_CRON', true);
    volumes:
      - wp-core:/var/www/html
      - ./data/wp:/var/www/html/wp-content
      - ./php/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.27
    container_name: wp-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - wp-core:/var/www/html:ro
      - ./data/wp:/var/www/html/wp-content:ro
    depends_on:
      - php

  cron:
    image: curlimages/curl:8.8.0
    container_name: wp-cron
    restart: unless-stopped
    entrypoint: [ "sh", "-c" ]
    command: |
      while true; do
        curl -s -m 20 http://nginx/wp-cron.php?doing_wp_cron=1 >/dev/null 2>&1;
        sleep 60;
      done
    depends_on:
      - nginx

volumes:
  redis-data:
  wp-core:


